apiVersion: apps/v1
kind:  Deployment
metadata: 
  name: deploy
  labels:
    app: depapp
spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
            maxSurge: 1     # Maximum number of pods that can be created over the desired replicas
            maxUnavailable: 1  # Maximum number of pods that can be unavailable during the update
    selector: 
      #matchExpressions:      
         #  -  { key: app, operator: In , values: [rsapp,  new-app]}
         #   -  { key: app, operator: Exists}
      matchLabels: 
          app: depapp
    replicas: 10
    template:
      metadata:
        labels:
          name: nginxapp
          app: depapp
      spec:
        containers:
          - name: nginxapp
            image: nginx:latest 
            ports:
                - containerPort: 80
                  protocol: TCP
                  

#https://www.apwide.com/8-deployment-strategies-explained-and-compared/
#https://spacelift.io/blog/kubernetes-deployment-strategies
#https://spot.io/resources/kubernetes-autoscaling/8-kubernetes-deployment-strategies/
