apiVersion: v1
metadata: 
    name: ci-tomcatappservice
kind: Service
spec: 
    selector:
        app: my-tomcatapp
    type: ClusterIP
    ports:
      - protocol: TCP 
        port: 8080 
        targetPort: 8080
        