apiVersion: v1
kind: Service
metadata: 
  name: backendsrv
spec:
  type: ClusterIP
  selector:
    app: deployappback 
  ports:
    - port: 8080
      targetPort: 8080
      name: tomcat
      protocol: TCP