apiVersion:  v1 
kind: Service
metadata:
   name: clusterip
   labels:
     app: clusterip 
spec:
    selector:
         app: nginx 
    ports:
       - protocol: TCP
         port: 80
    type: ClusterIP
    
